model_list:
  - model_name: deepseek-v3.2
    litellm_params:
      model: openai/deepseek-v3.2
      api_base: https://ollama.com/v1
      api_key: os.environ/OLLAMA_KEY_1

  - model_name: deepseek-v3.2
    litellm_params:
      model: openai/deepseek-v3.2
      api_base: https://ollama.com/v1
      api_key: os.environ/OLLAMA_KEY_2

  - model_name: deepseek-v3.2
    litellm_params:
      model: openai/deepseek-v3.2
      api_base: https://ollama.com/v1
      api_key: os.environ/OLLAMA_KEY_3

  - model_name: deepseek-v3.2
    litellm_params:
      model: openai/deepseek-v3.2
      api_base: https://ollama.com/v1
      api_key: os.environ/OLLAMA_KEY_4

router_settings:
  routing_strategy: least-busy